### ISSUE TITLE
[FEAT] Ranking 뷰 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [Kyo-Pig/Mega-Pig#20]
### 문제 상황
- 푸드 토너먼트 결과를 출력하는 랭킹 뷰의 부재

### 해결 방안
- 랭킹 뷰 추가
 
### TODO
- [x] 랭킹 뷰 전반적인 레이아웃 구성
- [x] 랭킹 뷰 내부 요소 지정

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 

---
> 진행 상황은 Comment로 아래에 달아주세요
ex) 220405: 00 추가

**Comment by commitcomplete** [comment]
완료
